import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StickyNavbar from "./_components/navbar-sticky";
import MobileNavbar from "./_components/navbar-mobile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StickyNavbar />
        <MobileNavbar />
        {children}
      </body>
    </html>
  );
}
